[package]
name = "tinyverse_tui"
version = "0.1.0"
edition = "2024"

[dependencies]
ansi-to-tui = "8.0.0"
anyhow = { version = "1.0.101", features = ["backtrace"] }
crossterm = "0.29.0"
ratatui = "0.29.0"
ratatui-core = "0.1.0"
reqwest = { version = "0.12.24", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde_json = "1.0.149"
tinyverse_lib = { path = "../tinyverse_lib" }
tinyverse_tui_components = { path = "../tinyverse_tui_components" }

[dev-dependencies]
chrono = "0.4.42"
insta = "1.46.3"
