use ratatui::style::Color;

/// Default theme palette used by shared components.
#[derive(Debug, Clone)]
pub struct ComponentTheme {
    pub base_bg: Color,
    pub surface_bg: Color,
    pub pill_ok_fg: Color,
    pub pill_ok_bg: Color,
    pub pill_warn_fg: Color,
    pub pill_warn_bg: Color,
    pub pill_err_fg: Color,
    pub pill_err_bg: Color,
    pub pill_info_fg: Color,
    pub pill_info_bg: Color,
    pub pill_muted_fg: Color,
    pub pill_muted_bg: Color,
    pub pill_accent_fg: Color,
    pub pill_accent_bg: Color,
    pub key_hint_key_fg: Color,
    pub key_hint_key_bg: Color,
    pub key_hint_action_fg: Color,
    pub key_hint_bracket_fg: Color,
    pub pane_focused_border: Color,
    pub pane_unfocused_border: Color,
    pub text_secondary: Color,
    pub text_muted: Color,
    pub text_primary: Color,
    pub selected_card_bg: Color,
    pub chat_separator_fg: Color,
    pub chat_card_border_fg: Color,
    pub chat_header_user_bg: Color,
    pub chat_header_agent_bg: Color,
    pub chat_header_system_bg: Color,
    pub chat_collapsible_bg: Color,
    pub chat_collapsible_focused_bg: Color,
    pub chat_collapsible_tag_bg: Color,
    pub chat_code_bg: Color,
    pub path_pill_fg: Color,
    pub path_pill_bg: Color,
    pub tree_tint_session: Color,
    pub tree_tint_console: Color,
    pub tree_tint_agent: Color,
    pub tree_tint_chat: Color,
    pub tree_tint_thread: Color,
    pub tree_badge_fg: Color,
    pub tree_badge_bg: Color,
}

impl Default for ComponentTheme {
    fn default() -> Self {
        Self {
            // ZSH cyber-sleek style guide palette (xterm-256 indices):
            // base 235, dark 237, medium 240, secondary text 250,
            // primary text 255, with dual accents:
            // - warm orange accent: 172 (slightly less bright than 208)
            // - cool cyan accent: 74/24 for contrast and balance.
            base_bg: Color::Indexed(235),
            surface_bg: Color::Indexed(237),
            pill_ok_fg: Color::Indexed(255),
            pill_ok_bg: Color::Indexed(240),
            pill_warn_fg: Color::Indexed(255),
            pill_warn_bg: Color::Indexed(172),
            pill_err_fg: Color::Indexed(255),
            pill_err_bg: Color::Indexed(166),
            pill_info_fg: Color::Indexed(255),
            pill_info_bg: Color::Indexed(24),
            pill_muted_fg: Color::Indexed(250),
            pill_muted_bg: Color::Indexed(237),
            pill_accent_fg: Color::Indexed(255),
            pill_accent_bg: Color::Indexed(172),
            key_hint_key_fg: Color::Indexed(255),
            key_hint_key_bg: Color::Indexed(240),
            key_hint_action_fg: Color::Indexed(250),
            key_hint_bracket_fg: Color::Indexed(240),
            pane_focused_border: Color::Indexed(74),
            pane_unfocused_border: Color::Indexed(240),
            text_secondary: Color::Indexed(252),
            text_muted: Color::Indexed(247),
            text_primary: Color::Indexed(255),
            selected_card_bg: Color::Indexed(237),
            chat_separator_fg: Color::Indexed(240),
            chat_card_border_fg: Color::Indexed(243),
            chat_header_user_bg: Color::Rgb(54, 45, 80),
            chat_header_agent_bg: Color::Rgb(26, 77, 100),
            chat_header_system_bg: Color::Indexed(94),
            chat_collapsible_bg: Color::Indexed(235),
            chat_collapsible_focused_bg: Color::Indexed(237),
            chat_collapsible_tag_bg: Color::Indexed(240),
            chat_code_bg: Color::Indexed(235),
            path_pill_fg: Color::Indexed(117),
            path_pill_bg: Color::Indexed(24),
            tree_tint_session: Color::Rgb(34, 30, 24),
            tree_tint_console: Color::Rgb(24, 28, 34),
            tree_tint_agent: Color::Rgb(30, 26, 36),
            tree_tint_chat: Color::Rgb(22, 32, 32),
            tree_tint_thread: Color::Rgb(24, 30, 28),
            tree_badge_fg: Color::Rgb(120, 120, 120),
            tree_badge_bg: Color::Rgb(36, 36, 36),
        }
    }
}
